'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5420
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ismaelWii.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bootm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bootm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bootmiiuse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bootmiiuse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brawl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brawl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property brick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property burn1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("burn1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property burn2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("burn2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property burn3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("burn3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cargado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cargado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cios2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cios2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cios3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cios3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property csdlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csdlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Porción de la memoria que carga antes que el menú de Wii, y que puede servir para prevenir bricks si tiene bug trucha y permite la instalación de Bootmii como Boot2..
        '''</summary>
        Friend ReadOnly Property def_boot2() As String
            Get
                Return ResourceManager.GetString("def_boot2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Literalmente &quot;ladrillo&quot;, se denomina así al mal funcionamiento de la consola que impide operar con ella, por lo que se convierte en un ladrillo o pisapapeles. Normalmente suelen producirse por manejar aplicaciones peligrosas sin conocimiento o por la instalación de WADs corruptos o incorrectos, por lo que debes evitar este tipo de prácitcas y ajustarte a las instrucciones de los tutoriales mientras aprendes..
        '''</summary>
        Friend ReadOnly Property def_brick() As String
            Get
                Return ResourceManager.GetString("def_brick", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es un IOS parcheado (véase IOS), para obtener funciones extra no incluidas en los originales, como cargar desde USB, DVD, mayor velocidad de USB, etc.
        '''Algunos mezclan IOS para obtener diversas funciones. Todos ellos tienen el bug trucha, que les permite instalar títulos en la Wii sin la firma de NintENdo.
        '''.
        '''</summary>
        Friend ReadOnly Property def_cios() As String
            Get
                Return ResourceManager.GetString("def_cios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es como un IOS (véase IOS) que dota a la Wii de las funciones necesarias para reproducir juegos de Gamecube. cMIOS convierte la Wii en una GC, deshabilitando el acceso a todas las funciones exclusivas de Wii, incluso bajando la potencia de su procesador..
        '''</summary>
        Friend ReadOnly Property def_cmios() As String
            Get
                Return ResourceManager.GetString("def_cmios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es la unidad de funcionamiento básica del firmware de la Wii. Para simplificarlo, un IOS vendría a ser un archivo que se carga en el procesador de la Wii y sirve para que un recurso (Un juego, un canal) funcione. Los IOS se instalan en posiciones que van de la 1 a la 255, pudiéndose cargar solo uno a la vez. Por ejemplo, algunos juegos como el Mario Kart usan el IOS26 para funcionar, otros usan el IOS53, etc. Cada IOS se instala y ejecuta de forma independiente de los demás, por lo que no interfieren entre  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property def_ios() As String
            Get
                Return ResourceManager.GetString("def_ios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System Menu:
        '''
        '''Es el menú del Sistema, lo que ves al encender la Wii y que usas para cargar los canales. 
        '''Carga después de boot2, y si no dispones de una protección como bootmii en boot2 o priiloader, puede causar un brick si lo dañas o si dañas el IOS sobre el que funciona..
        '''</summary>
        Friend ReadOnly Property def_systemmenu() As String
            Get
                Return ResourceManager.GetString("def_systemmenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aplicación homebrew que funciona como cargador de juegos, permitiendo cargar backups que no se pueden lanzar desde el Canal Disco. Los loaders utilizan los cIOS en lugar de los IOS oficiales para poder cargar backups, por lo que no pueden funcionar sin ellos..
        '''</summary>
        Friend ReadOnly Property def_usbloader() As String
            Get
                Return ResourceManager.GetString("def_usbloader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Un WAD es un archivo de instalación el cual instala contenido en tu Wii, ya sean canales o IOS, System Menus u otros contenidos..
        '''</summary>
        Friend ReadOnly Property def_wad() As String
            Get
                Return ResourceManager.GetString("def_wad", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property dvd12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvd12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DVD2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DVD2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DVD21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DVD21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dvd3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvd3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dvd31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvd31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dvdlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvdlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property facebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder08_OpenYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder08-OpenYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property googlecode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("googlecode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guardar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guardar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hbc11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hbc11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hbc21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hbc21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hbc31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hbc31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imageninicial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageninicial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iniciochristmas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iniciochristmas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lbat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lbat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property legoindiana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("legoindiana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property link() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("link", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ljones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ljones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property load() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("load", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logov4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logov4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lwars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lwars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No puedes continuar, ya que al estar en la versión 4.3, necesitas un juego para poder instalar el Homebrew Channel o usar cualquier homebrew....
        '''</summary>
        Friend ReadOnly Property mensaje_fin_43() As String
            Get
                Return ResourceManager.GetString("mensaje_fin_43", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property minibootm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minibootm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miniburn1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniburn1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miniburn2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniburn2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miniburn3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniburn3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minicios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minicios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minicios2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minicios2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minicios3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minicios3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minidvd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minidvd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minidvd3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minidvd3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minihbc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minihbc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minihbc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minihbc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minihbc3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minihbc3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miniusb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniusb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miniusb2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniusb2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property miniusb3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniusb3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nextimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nextimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property no_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property organizacion_hbc_img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("organizacion_hbc_img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property priiloader1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("priiloader1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property priiloader2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("priiloader2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property priiloader3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("priiloader3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SSBB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SSBB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tales_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tales_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Atención: Tienes una versión de firmware muy antigua. Para hacer este tutorial, actualiza con algún juego como New Super Mario Bros o cualquier otro para actualizar a una versión superior. No actualices por internet, ya que necesitarás en ese caso un juego especial para poder realizar el proceso..
        '''</summary>
        Friend ReadOnly Property tuto_error() As String
            Get
                Return ResourceManager.GetString("tuto_error", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property tutobootmii1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tutobootmii1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property twitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property update2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updatecios1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updatecios1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updatecios2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updatecios2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updatecios3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updatecios3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property updatecios31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updatecios31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usb2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usb2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usb3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usb3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usblogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usblogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wad1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wad1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wad2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wad2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wad3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wad3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wheelie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wheelie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property youtube() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youtube", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property youtubeicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youtubeicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property YUGIOH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YUGIOH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
